### ISSUE TITLE
你好 大佬 这个确少了 sql脚本

### ISSUE THREAD

**Issue by dahai4567** [carbule-bar/java-ffmpeg#2]
你好 大佬 这个确少了 sql脚本 谢谢了

**Comment by carbule-bar** [comment]
数据库这边的话我已经找不到了 因为项目很简单 你这边可以根据Account.class和Video.class推断出数据库的表结构的

**Comment by dahai4567** [comment]
好的 大佬 那我就反推一下了 大佬 我留一个qq 加一个qq哈 有不懂的问题 向你请教哈 我对视频转码这一块也非常感兴趣

**Comment by dahai4567** [comment]
3491441506
